typography_spectrum: 0.3673599923495203
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5703875303734094
  lightness: 0.9359098700806499
  saturation: 0.3947317225392908
  rhythmicContrast: 0.23242783197201788
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5578717838507146
analytics:
  google: null
  facebook: null
  twitter: null
name: Luis Alt
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Service + Business + Design
purpose: []
